# Generated by Django 5.0.7 on 2024-08-14 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField(null=True)),
                ('rating', models.IntegerField(choices=[('Bad', 1), ('Not Bad', 2), ('Good', 3), ('Excellent', 4), ('Fantastic', 5)])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musician.musicians')),
            ],
        ),
    ]
