# Generated by Django 5.0.7 on 2024-08-14 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0001_initial'),
        ('Musician', '0002_alter_musicians_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Musician.musicians'),
        ),
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
