# Generated by Django 5.0.7 on 2024-08-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicians',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
